apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    # Add provider-specific annotations here
spec:
  selector:
    app: longhorn-ui
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 192.168.201.4 # Static IP for LongHorn

# This is a configuration on top of the Longhorn application.yaml
