kind: Namespace
apiVersion: v1
metadata:
  name: homer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
  labels:
    app: homer
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - image: b4bz/homer:v25.03.3
          name: homer
          volumeMounts:
            - name: assets
              mountPath: /www/assets
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 64Mi
              ephemeral-storage: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: homer-pvc
            readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homer-pvc
  namespace: homer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: homer
spec:
  selector:
    app: homer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort
