kind: Namespace
apiVersion: v1
metadata:
  name: podinfo-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-test
  namespace: podinfo-test
spec:
  selector:
    matchLabels:
      app: podinfo-test
  template:
    metadata:
      labels:
        app: podinfo-test
    spec:
      containers:
        - name: podinfo-test-pod
          image: stefanprodan/podinfo
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-test
  namespace: podinfo-test
spec:
  type: LoadBalancer
  selector:
    app: podinfo-test
  ports:
    - port: 9898
      targetPort: 9898
