apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: http
  hostnames:
    - "argocd.delgaudio.dev"
  rules:
    - backendRefs:
        - name: argocd-application-server
          port: 80
